// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// validatableAll is an autogenerated mock type for the validatableAll type
type validatableAll struct {
	mock.Mock
}

// ValidateAll provides a mock function with given fields:
func (_m *validatableAll) ValidateAll() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewValidatableAll interface {
	mock.TestingT
	Cleanup(func())
}

// newValidatableAll creates a new instance of validatableAll. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newValidatableAll(t mockConstructorTestingTnewValidatableAll) *validatableAll {
	mock := &validatableAll{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
