// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// validatable is an autogenerated mock type for the validatable type
type validatable struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *validatable) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewValidatable interface {
	mock.TestingT
	Cleanup(func())
}

// newValidatable creates a new instance of validatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newValidatable(t mockConstructorTestingTnewValidatable) *validatable {
	mock := &validatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
