// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: realm_mgr/v1/common.proto

package realm_mgr_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumStatus int32

const (
	EnumStatus_ENUM_STATUS_UNSPECIFIED EnumStatus = 0
	EnumStatus_ENUM_STATUS_ACTIVE      EnumStatus = 1
	EnumStatus_ENUM_STATUS_DRAFT       EnumStatus = 2
	EnumStatus_ENUM_STATUS_DISABLED    EnumStatus = 3
	EnumStatus_ENUM_STATUS_DELETED     EnumStatus = 4
)

// Enum value maps for EnumStatus.
var (
	EnumStatus_name = map[int32]string{
		0: "ENUM_STATUS_UNSPECIFIED",
		1: "ENUM_STATUS_ACTIVE",
		2: "ENUM_STATUS_DRAFT",
		3: "ENUM_STATUS_DISABLED",
		4: "ENUM_STATUS_DELETED",
	}
	EnumStatus_value = map[string]int32{
		"ENUM_STATUS_UNSPECIFIED": 0,
		"ENUM_STATUS_ACTIVE":      1,
		"ENUM_STATUS_DRAFT":       2,
		"ENUM_STATUS_DISABLED":    3,
		"ENUM_STATUS_DELETED":     4,
	}
)

func (x EnumStatus) Enum() *EnumStatus {
	p := new(EnumStatus)
	*p = x
	return p
}

func (x EnumStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_realm_mgr_v1_common_proto_enumTypes[0].Descriptor()
}

func (EnumStatus) Type() protoreflect.EnumType {
	return &file_realm_mgr_v1_common_proto_enumTypes[0]
}

func (x EnumStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumStatus.Descriptor instead.
func (EnumStatus) EnumDescriptor() ([]byte, []int) {
	return file_realm_mgr_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_realm_mgr_v1_common_proto protoreflect.FileDescriptor

var file_realm_mgr_v1_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2a, 0x8b, 0x01, 0x0a, 0x0a, 0x45, 0x6e,
	0x75, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x4e, 0x55, 0x4d,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a,
	0x11, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x52, 0x41,
	0x46, 0x54, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x17,
	0x0a, 0x13, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x04, 0x42, 0x1b, 0x5a, 0x19, 0x72, 0x65, 0x61, 0x6c, 0x6d,
	0x5f, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67,
	0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_realm_mgr_v1_common_proto_rawDescOnce sync.Once
	file_realm_mgr_v1_common_proto_rawDescData = file_realm_mgr_v1_common_proto_rawDesc
)

func file_realm_mgr_v1_common_proto_rawDescGZIP() []byte {
	file_realm_mgr_v1_common_proto_rawDescOnce.Do(func() {
		file_realm_mgr_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_realm_mgr_v1_common_proto_rawDescData)
	})
	return file_realm_mgr_v1_common_proto_rawDescData
}

var file_realm_mgr_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_realm_mgr_v1_common_proto_goTypes = []interface{}{
	(EnumStatus)(0), // 0: realm_mgr.v1.EnumStatus
}
var file_realm_mgr_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realm_mgr_v1_common_proto_init() }
func file_realm_mgr_v1_common_proto_init() {
	if File_realm_mgr_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_realm_mgr_v1_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_realm_mgr_v1_common_proto_goTypes,
		DependencyIndexes: file_realm_mgr_v1_common_proto_depIdxs,
		EnumInfos:         file_realm_mgr_v1_common_proto_enumTypes,
	}.Build()
	File_realm_mgr_v1_common_proto = out.File
	file_realm_mgr_v1_common_proto_rawDesc = nil
	file_realm_mgr_v1_common_proto_goTypes = nil
	file_realm_mgr_v1_common_proto_depIdxs = nil
}
