// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: realm_mgr/v1/realm.proto

package realm_mgr_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Realm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID identifier of the realm
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the realm
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the realm
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Current realm status
	Status EnumStatus `protobuf:"varint,4,opt,name=status,proto3,enum=realm_mgr.v1.EnumStatus" json:"status,omitempty"`
	// Created at timestamp of the realm
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at timestamp of the realm
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Realm) Reset() {
	*x = Realm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Realm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Realm) ProtoMessage() {}

func (x *Realm) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Realm.ProtoReflect.Descriptor instead.
func (*Realm) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{0}
}

func (x *Realm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Realm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Realm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Realm) GetStatus() EnumStatus {
	if x != nil {
		return x.Status
	}
	return EnumStatus_ENUM_STATUS_UNSPECIFIED
}

func (x *Realm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Realm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetRealmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID identifier of the realm
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Realm status to be returned
	Status EnumStatus `protobuf:"varint,2,opt,name=status,proto3,enum=realm_mgr.v1.EnumStatus" json:"status,omitempty"`
}

func (x *GetRealmRequest) Reset() {
	*x = GetRealmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealmRequest) ProtoMessage() {}

func (x *GetRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealmRequest.ProtoReflect.Descriptor instead.
func (*GetRealmRequest) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{1}
}

func (x *GetRealmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRealmRequest) GetStatus() EnumStatus {
	if x != nil {
		return x.Status
	}
	return EnumStatus_ENUM_STATUS_UNSPECIFIED
}

type GetRealmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm *Realm `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *GetRealmResponse) Reset() {
	*x = GetRealmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealmResponse) ProtoMessage() {}

func (x *GetRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealmResponse.ProtoReflect.Descriptor instead.
func (*GetRealmResponse) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{2}
}

func (x *GetRealmResponse) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

type CreateRealmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the realm to be created
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the realm to be created
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateRealmRequest) Reset() {
	*x = CreateRealmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmRequest) ProtoMessage() {}

func (x *CreateRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmRequest.ProtoReflect.Descriptor instead.
func (*CreateRealmRequest) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRealmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRealmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRealmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm *Realm `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *CreateRealmResponse) Reset() {
	*x = CreateRealmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRealmResponse) ProtoMessage() {}

func (x *CreateRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRealmResponse.ProtoReflect.Descriptor instead.
func (*CreateRealmResponse) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRealmResponse) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

type ReleaseRealmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID identifier of the realm
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReleaseRealmRequest) Reset() {
	*x = ReleaseRealmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRealmRequest) ProtoMessage() {}

func (x *ReleaseRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRealmRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRealmRequest) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRealmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReleaseRealmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm *Realm `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *ReleaseRealmResponse) Reset() {
	*x = ReleaseRealmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRealmResponse) ProtoMessage() {}

func (x *ReleaseRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRealmResponse.ProtoReflect.Descriptor instead.
func (*ReleaseRealmResponse) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseRealmResponse) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

type UpdateRealmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm *Realm `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *UpdateRealmRequest) Reset() {
	*x = UpdateRealmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRealmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealmRequest) ProtoMessage() {}

func (x *UpdateRealmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealmRequest.ProtoReflect.Descriptor instead.
func (*UpdateRealmRequest) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRealmRequest) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

type UpdateRealmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Realm *Realm `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
}

func (x *UpdateRealmResponse) Reset() {
	*x = UpdateRealmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_realm_mgr_v1_realm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRealmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealmResponse) ProtoMessage() {}

func (x *UpdateRealmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_mgr_v1_realm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealmResponse.ProtoReflect.Descriptor instead.
func (*UpdateRealmResponse) Descriptor() ([]byte, []int) {
	return file_realm_mgr_v1_realm_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRealmResponse) GetRealm() *Realm {
	if x != nil {
		return x.Realm
	}
	return nil
}

var File_realm_mgr_v1_realm_proto protoreflect.FileDescriptor

var file_realm_mgr_v1_realm_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f,
	0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x02, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x12, 0x18,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72,
	0x03, 0xb0, 0x01, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f,
	0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x5d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x22, 0x53, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x65, 0x61,
	0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x6d,
	0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x05, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x22, 0x2f, 0x0a, 0x13, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xb0, 0x01,
	0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x6c,
	0x6d, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x22, 0x3f, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61,
	0x6c, 0x6d, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x22, 0x40, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x61, 0x6c, 0x6d, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x6d, 0x42, 0x1b, 0x5a, 0x19, 0x72,
	0x65, 0x61, 0x6c, 0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x65, 0x61, 0x6c,
	0x6d, 0x5f, 0x6d, 0x67, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_realm_mgr_v1_realm_proto_rawDescOnce sync.Once
	file_realm_mgr_v1_realm_proto_rawDescData = file_realm_mgr_v1_realm_proto_rawDesc
)

func file_realm_mgr_v1_realm_proto_rawDescGZIP() []byte {
	file_realm_mgr_v1_realm_proto_rawDescOnce.Do(func() {
		file_realm_mgr_v1_realm_proto_rawDescData = protoimpl.X.CompressGZIP(file_realm_mgr_v1_realm_proto_rawDescData)
	})
	return file_realm_mgr_v1_realm_proto_rawDescData
}

var file_realm_mgr_v1_realm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_realm_mgr_v1_realm_proto_goTypes = []interface{}{
	(*Realm)(nil),                 // 0: realm_mgr.v1.Realm
	(*GetRealmRequest)(nil),       // 1: realm_mgr.v1.GetRealmRequest
	(*GetRealmResponse)(nil),      // 2: realm_mgr.v1.GetRealmResponse
	(*CreateRealmRequest)(nil),    // 3: realm_mgr.v1.CreateRealmRequest
	(*CreateRealmResponse)(nil),   // 4: realm_mgr.v1.CreateRealmResponse
	(*ReleaseRealmRequest)(nil),   // 5: realm_mgr.v1.ReleaseRealmRequest
	(*ReleaseRealmResponse)(nil),  // 6: realm_mgr.v1.ReleaseRealmResponse
	(*UpdateRealmRequest)(nil),    // 7: realm_mgr.v1.UpdateRealmRequest
	(*UpdateRealmResponse)(nil),   // 8: realm_mgr.v1.UpdateRealmResponse
	(EnumStatus)(0),               // 9: realm_mgr.v1.EnumStatus
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_realm_mgr_v1_realm_proto_depIdxs = []int32{
	9,  // 0: realm_mgr.v1.Realm.status:type_name -> realm_mgr.v1.EnumStatus
	10, // 1: realm_mgr.v1.Realm.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: realm_mgr.v1.Realm.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: realm_mgr.v1.GetRealmRequest.status:type_name -> realm_mgr.v1.EnumStatus
	0,  // 4: realm_mgr.v1.GetRealmResponse.realm:type_name -> realm_mgr.v1.Realm
	0,  // 5: realm_mgr.v1.CreateRealmResponse.realm:type_name -> realm_mgr.v1.Realm
	0,  // 6: realm_mgr.v1.ReleaseRealmResponse.realm:type_name -> realm_mgr.v1.Realm
	0,  // 7: realm_mgr.v1.UpdateRealmRequest.realm:type_name -> realm_mgr.v1.Realm
	0,  // 8: realm_mgr.v1.UpdateRealmResponse.realm:type_name -> realm_mgr.v1.Realm
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_realm_mgr_v1_realm_proto_init() }
func file_realm_mgr_v1_realm_proto_init() {
	if File_realm_mgr_v1_realm_proto != nil {
		return
	}
	file_realm_mgr_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_realm_mgr_v1_realm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Realm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRealmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRealmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRealmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseRealmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseRealmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRealmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_realm_mgr_v1_realm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRealmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_realm_mgr_v1_realm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_realm_mgr_v1_realm_proto_goTypes,
		DependencyIndexes: file_realm_mgr_v1_realm_proto_depIdxs,
		MessageInfos:      file_realm_mgr_v1_realm_proto_msgTypes,
	}.Build()
	File_realm_mgr_v1_realm_proto = out.File
	file_realm_mgr_v1_realm_proto_rawDesc = nil
	file_realm_mgr_v1_realm_proto_goTypes = nil
	file_realm_mgr_v1_realm_proto_depIdxs = nil
}
