// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrInfoExtractor is an autogenerated mock type for the ErrInfoExtractor type
type ErrInfoExtractor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ErrInfoExtractor) Execute(_a0 error) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(error) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewErrInfoExtractor interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrInfoExtractor creates a new instance of ErrInfoExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrInfoExtractor(t mockConstructorTestingTNewErrInfoExtractor) *ErrInfoExtractor {
	mock := &ErrInfoExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
