// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	pgdb "github.com/alexZaicev/realm-mgr/internal/drivers/pgdb"
	mock "github.com/stretchr/testify/mock"
)

// DBOptionFunc is an autogenerated mock type for the DBOptionFunc type
type DBOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DBOptionFunc) Execute(_a0 *pgdb.DBOptions) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewDBOptionFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewDBOptionFunc creates a new instance of DBOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDBOptionFunc(t mockConstructorTestingTNewDBOptionFunc) *DBOptionFunc {
	mock := &DBOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
