// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hook is an autogenerated mock type for the Hook type
type Hook struct {
	mock.Mock
}

// Before provides a mock function with given fields: query, args
func (_m *Hook) Before(query string, args ...interface{}) func() {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 func()
	if rf, ok := ret.Get(0).(func(string, ...interface{}) func()); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

type mockConstructorTestingTNewHook interface {
	mock.TestingT
	Cleanup(func())
}

// NewHook creates a new instance of Hook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHook(t mockConstructorTestingTNewHook) *Hook {
	mock := &Hook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
