// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/alexZaicev/realm-mgr/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	realms "github.com/alexZaicev/realm-mgr/internal/usecases/realms"
)

// RealmUpdater is an autogenerated mock type for the RealmUpdater type
type RealmUpdater struct {
	mock.Mock
}

// UpdateRealm provides a mock function with given fields: ctx, repos, input
func (_m *RealmUpdater) UpdateRealm(ctx context.Context, repos realms.UpdateRealmRepos, input realms.UpdateRealmInput) (entities.Realm, error) {
	ret := _m.Called(ctx, repos, input)

	var r0 entities.Realm
	if rf, ok := ret.Get(0).(func(context.Context, realms.UpdateRealmRepos, realms.UpdateRealmInput) entities.Realm); ok {
		r0 = rf(ctx, repos, input)
	} else {
		r0 = ret.Get(0).(entities.Realm)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, realms.UpdateRealmRepos, realms.UpdateRealmInput) error); ok {
		r1 = rf(ctx, repos, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRealmUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewRealmUpdater creates a new instance of RealmUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRealmUpdater(t mockConstructorTestingTNewRealmUpdater) *RealmUpdater {
	mock := &RealmUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
