// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeRealmManagerServiceServer is an autogenerated mock type for the UnsafeRealmManagerServiceServer type
type UnsafeRealmManagerServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedRealmManagerServiceServer provides a mock function with given fields:
func (_m *UnsafeRealmManagerServiceServer) mustEmbedUnimplementedRealmManagerServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeRealmManagerServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeRealmManagerServiceServer creates a new instance of UnsafeRealmManagerServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeRealmManagerServiceServer(t mockConstructorTestingTNewUnsafeRealmManagerServiceServer) *UnsafeRealmManagerServiceServer {
	mock := &UnsafeRealmManagerServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
