name: checks
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@${MOCKERY_INSTALL_VERSION}
        env:
          MOCKERY_INSTALL_VERSION: v2.14.0
      - name: Install Wire
        run: go install github.com/google/wire/cmd/wire@${WIRE_VERSION}
        env:
          WIRE_VERSION: v0.5.0
      - name: Install GoImports
        run: go install golang.org/x/tools/cmd/goimports@${GOIMPORTS_VERSION}
        env:
          GOIMPORTS_VERSION: v0.1.12
      - name: Install GCI
        run: go install github.com/daixiang0/gci@${GCI_VERSION}
        env:
          GCI_VERSION: v0.8.0
      - name: Check committed code
        run: make -B checks dirty