name: Functional Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  runner-job:
    name: functional-tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Build
        run: make build
      - name: Run service
        run: nohup ./dist/realm-mgr-grpc &>/dev/null &
      - name: Run functional tests
        run: make functional
        env:
          FUNCTIONAL_TESTS_CONFIG_FILE: ./tests/functional/ci-config.yml

    services:
      postgres-ft:
        image: postgres:13.8
        ports:
          - 5432:5432
        env:
          - POSTGRES_HOST_AUTH_METHOD: trust
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: mysecret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5