name: golint
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Install golintci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
      - name: Run lint
        run: make lint


