name: Units Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  checks:
    name: unit-tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Run unit tests
        run: make unit
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.9
#      - name: Coveralls
#        uses: coverallsapp/github-action@1.1.3
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: coverage.lcov
