// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RealmManagerAuditRepository is an autogenerated mock type for the RealmManagerAuditRepository type
type RealmManagerAuditRepository struct {
	mock.Mock
}

type mockConstructorTestingTNewRealmManagerAuditRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRealmManagerAuditRepository creates a new instance of RealmManagerAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRealmManagerAuditRepository(t mockConstructorTestingTNewRealmManagerAuditRepository) *RealmManagerAuditRepository {
	mock := &RealmManagerAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
